<?php

namespace App\Models;

use App\Scopes\BuyerScope;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Buyer extends User
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new BuyerScope());
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}
